create table STOCK(
	ID INTEGER PRIMARY KEY,
	PRODUCT_NAME varchar(255) NOT null,
	QUANTITY INT NOT null
);

INSERT INTO STOCK (PRODUCT_NAME, QUANTITY) VALUES ('Maçã', 10);
INSERT INTO STOCK (PRODUCT_NAME, QUANTITY) VALUES ('Maçã Verde', 15);
INSERT INTO STOCK (PRODUCT_NAME, QUANTITY) VALUES ('Mamão', 20);